server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: sysmonitor-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: sysmonitor
      __path__: /app/logs/*.log
      
- job_name: system-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: system
      __path__: /var/log/*.log

- job_name: journal
  journal:
    max_age: 12h
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
    - source_labels: ['__journal__hostname']
      target_label: 'hostname'
    - source_labels: ['__journal_syslog_identifier']
      target_label: 'syslog_identifier'